# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AddXYToPlot.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AddXYToPlot.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x41\x64\x64XYToPlot.proto\"V\n\x0b\x41\x64\x64XYToPlot\x12\x13\n\x0bplot_number\x18\x01 \x02(\r\x12\x12\n\ndata_label\x18\x02 \x02(\t\x12\x0e\n\x06\x64\x61ta_x\x18\x03 \x02(\x02\x12\x0e\n\x06\x64\x61ta_y\x18\x04 \x02(\x02'
)




_ADDXYTOPLOT = _descriptor.Descriptor(
  name='AddXYToPlot',
  full_name='AddXYToPlot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='plot_number', full_name='AddXYToPlot.plot_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_label', full_name='AddXYToPlot.data_label', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_x', full_name='AddXYToPlot.data_x', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_y', full_name='AddXYToPlot.data_y', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['AddXYToPlot'] = _ADDXYTOPLOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddXYToPlot = _reflection.GeneratedProtocolMessageType('AddXYToPlot', (_message.Message,), {
  'DESCRIPTOR' : _ADDXYTOPLOT,
  '__module__' : 'AddXYToPlot_pb2'
  # @@protoc_insertion_point(class_scope:AddXYToPlot)
  })
_sym_db.RegisterMessage(AddXYToPlot)


# @@protoc_insertion_point(module_scope)
