# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClearPlots.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ClearPlots.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x43learPlots.proto\"\x0c\n\nClearPlots'
)




_CLEARPLOTS = _descriptor.Descriptor(
  name='ClearPlots',
  full_name='ClearPlots',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=32,
)

DESCRIPTOR.message_types_by_name['ClearPlots'] = _CLEARPLOTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClearPlots = _reflection.GeneratedProtocolMessageType('ClearPlots', (_message.Message,), {
  'DESCRIPTOR' : _CLEARPLOTS,
  '__module__' : 'ClearPlots_pb2'
  # @@protoc_insertion_point(class_scope:ClearPlots)
  })
_sym_db.RegisterMessage(ClearPlots)


# @@protoc_insertion_point(module_scope)
