# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CLIData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CLIData.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rCLIData.proto\"\x16\n\x07\x43LIData\x12\x0b\n\x03msg\x18\x01 \x02(\x0c'
)




_CLIDATA = _descriptor.Descriptor(
  name='CLIData',
  full_name='CLIData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='CLIData.msg', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=39,
)

DESCRIPTOR.message_types_by_name['CLIData'] = _CLIDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CLIData = _reflection.GeneratedProtocolMessageType('CLIData', (_message.Message,), {
  'DESCRIPTOR' : _CLIDATA,
  '__module__' : 'CLIData_pb2'
  # @@protoc_insertion_point(class_scope:CLIData)
  })
_sym_db.RegisterMessage(CLIData)


# @@protoc_insertion_point(module_scope)
