# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DrawPlot.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DrawPlot.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x44rawPlot.proto\"[\n\x08\x44rawPlot\x12\x13\n\x0bplot_number\x18\x01 \x02(\r\x12\x12\n\ndata_label\x18\x02 \x02(\t\x12\x12\n\x06\x64\x61ta_x\x18\x03 \x03(\rB\x02\x10\x01\x12\x12\n\x06\x64\x61ta_y\x18\x04 \x03(\x02\x42\x02\x10\x01'
)




_DRAWPLOT = _descriptor.Descriptor(
  name='DrawPlot',
  full_name='DrawPlot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='plot_number', full_name='DrawPlot.plot_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_label', full_name='DrawPlot.data_label', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_x', full_name='DrawPlot.data_x', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_y', full_name='DrawPlot.data_y', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['DrawPlot'] = _DRAWPLOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DrawPlot = _reflection.GeneratedProtocolMessageType('DrawPlot', (_message.Message,), {
  'DESCRIPTOR' : _DRAWPLOT,
  '__module__' : 'DrawPlot_pb2'
  # @@protoc_insertion_point(class_scope:DrawPlot)
  })
_sym_db.RegisterMessage(DrawPlot)


_DRAWPLOT.fields_by_name['data_x']._options = None
_DRAWPLOT.fields_by_name['data_y']._options = None
# @@protoc_insertion_point(module_scope)
