# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DrawBodePlot.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DrawBodePlot.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x44rawBodePlot.proto\"|\n\x0c\x44rawBodePlot\x12\x13\n\x0bplot_number\x18\x01 \x02(\r\x12\x12\n\ndata_label\x18\x02 \x02(\t\x12\x15\n\tdata_freq\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x14\n\x08\x64\x61ta_mag\x18\x04 \x03(\x02\x42\x02\x10\x01\x12\x16\n\ndata_phase\x18\x05 \x03(\x02\x42\x02\x10\x01'
)




_DRAWBODEPLOT = _descriptor.Descriptor(
  name='DrawBodePlot',
  full_name='DrawBodePlot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='plot_number', full_name='DrawBodePlot.plot_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_label', full_name='DrawBodePlot.data_label', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_freq', full_name='DrawBodePlot.data_freq', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_mag', full_name='DrawBodePlot.data_mag', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_phase', full_name='DrawBodePlot.data_phase', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['DrawBodePlot'] = _DRAWBODEPLOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DrawBodePlot = _reflection.GeneratedProtocolMessageType('DrawBodePlot', (_message.Message,), {
  'DESCRIPTOR' : _DRAWBODEPLOT,
  '__module__' : 'DrawBodePlot_pb2'
  # @@protoc_insertion_point(class_scope:DrawBodePlot)
  })
_sym_db.RegisterMessage(DrawBodePlot)


_DRAWBODEPLOT.fields_by_name['data_freq']._options = None
_DRAWBODEPLOT.fields_by_name['data_mag']._options = None
_DRAWBODEPLOT.fields_by_name['data_phase']._options = None
# @@protoc_insertion_point(module_scope)
