# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LogPrint.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LogPrint.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eLogPrint.proto\"2\n\x08LogPrint\x12\x19\n\x11milliseconds_tick\x18\x01 \x02(\r\x12\x0b\n\x03msg\x18\x02 \x02(\t'
)




_LOGPRINT = _descriptor.Descriptor(
  name='LogPrint',
  full_name='LogPrint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='milliseconds_tick', full_name='LogPrint.milliseconds_tick', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='LogPrint.msg', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['LogPrint'] = _LOGPRINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogPrint = _reflection.GeneratedProtocolMessageType('LogPrint', (_message.Message,), {
  'DESCRIPTOR' : _LOGPRINT,
  '__module__' : 'LogPrint_pb2'
  # @@protoc_insertion_point(class_scope:LogPrint)
  })
_sym_db.RegisterMessage(LogPrint)


# @@protoc_insertion_point(module_scope)
