#ifndef PRIVATE_SIGNAL_RANGES_H_
#define PRIVATE_SIGNAL_RANGES_H_

#include "posted_signals.h"

// These define ranges of signals for each Active Object that it uses to define
// private signals that are not visible to any other AO.
enum PrivateSignalRanges
{
    PRIVATE_SIGNAL_RANGE_START = DISPATCHED_MAX_SIG,
    PRIVATE_SIGNAL_BLINKY_START,
    PRIVATE_SIGNAL_BLINKY_MAX = PRIVATE_SIGNAL_BLINKY_START + 10,
    PRIVATE_SIGNAL_DIRECTOR_START,
    PRIVATE_SIGNAL_DIRECTOR_MAX = PRIVATE_SIGNAL_DIRECTOR_START + 10,
    PRIVATE_SIGNAL_APP_CLI_START,
    PRIVATE_SIGNAL_APP_CLI_MAX = PRIVATE_SIGNAL_APP_CLI_START + 10,
    PRIVATE_SIGNAL_PC_COM_START,
    PRIVATE_SIGNAL_PC_COM_MAX = PRIVATE_SIGNAL_PC_COM_START + 10,
    PRIVATE_SIGNAL_ANALYZER_START,
    PRIVATE_SIGNAL_ANALAYZER_MAX = PRIVATE_SIGNAL_ANALYZER_START + 10,
    PRIVATE_SIGNAL_RANGE_MAX
};

#endif // PRIVATE_SIGNAL_RANGES_H_
